version: "3.9"
services:
  users:
    build:
      context: .
      dockerfile: ./users/Dockerfile
    ports:
      - "8081:8001"
    env_file:
      - config.env
    container_name: test_users
    depends_on:
      - database
  offers:
    build:
      context: .
      dockerfile: ./offers/Dockerfile
    ports:
      - "8082:8002"
    env_file:
      - config.env
    container_name: test_offers
    depends_on:
      - database
  database:
    image: "postgres"
    env_file:
      - db.env
    ports:
    - "19284:5432"
    container_name: test_psql
    volumes:
    - ./migration.sql:/docker-entrypoint-initdb.d/init.sql
#      - db-data:/var/lib/postgresql/data - my computer has some psql data there already, so I will not add that :)
