"""added title field to offers table

Revision ID: 4675f7f77a12
Revises: e87fdddfa319
Create Date: 2020-12-08 21:27:59.699098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4675f7f77a12'
down_revision = 'e87fdddfa319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'title')
    # ### end Alembic commands ###
