"""added salt field

Revision ID: 70ad0a56c17e
Revises: 4675f7f77a12
Create Date: 2020-12-09 11:36:35.510508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ad0a56c17e'
down_revision = '4675f7f77a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(), nullable=False))
    op.create_unique_constraint('salt_un', 'users', ['salt'])
    op.create_unique_constraint(None, 'users', ['salt'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('salt_un', 'users', type_='unique')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###
